server:
  port: 8888 # Config Server

spring:
  application:
    name: config-service
  config:
    import:
      - optional:classpath:.env[.properties]
      - optional:configtree:C:/dev/secrets/   # ← JKS가 없는 전용 폴더만 임포트

  cloud:
    config:
      server:
        git:
          uri: git@github.com:backend20250319/petful-config-repo.git # GitHub
          default-label: main
          ignoreLocalSshSettings: true

          strictHostKeyChecking: true
          hostKey: AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
          hostKeyAlgorithm: ssh-rsa
          privateKey: ${config_server_rsa}
          search-paths: /**

  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:password}

encrypt:
  key-store:
    location: file:${KEYSTORE_PATH}
    password: ${KEYSTORE_PASSWORD}
    alias: ${KEY_ALIAS}

# JWT 설정
jwt:
  secret: ${JWT_SECRET:your-secret-key-should-be-very-long-and-secure-for-production}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간 (밀리초)
